version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: collab-postgres
    environment:
      POSTGRES_DB: collab_editor
      POSTGRES_USER: collab
      POSTGRES_PASSWORD: collab
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: collab-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: collab-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongo_data:
